# This file serves as a template for the configuration file. Copy it and edit the values as needed.
# Use --config parameter to specify the path to the configuration file.

[db]
host = "localhost"
port = 3306
database = "flare_indexer"
username = "indexeruser"
password = "P.a.s.s.W.O.R.D"
log_queries = false

[logger]
level = "INFO"
file = "./logs/flare-indexer.log"
console = true

[metrics]
# used for prometheus metrics of the indexer
# currently, no specific data are included in the metrics in addition to the default ones
prometheus_address = "localhost:2112"

[chain]
node_url = "http://localhost:9650/"
address_hrp = "localflare"
chain_id = 162
# eth_rpc_url is needed for services
eth_rpc_url = "http://localhost:9650/ext/bc/C/rpc"
# api key may be needed for access to production nodes
api_key = ""
# private_key_file is needed for voting and mirroring clients
private_key_file = "path/to/private/key/file"

[x_chain_indexer]
enabled = false
timeout = "10s"
start_index = 5
batch_size = 10

[p_chain_indexer]
enabled = true
timeout = "10s"
start_index = 0
batch_size = 10

[uptime_cronjob]
enabled = false
timeout = "10s"
enable_voting = false
# start of the uptime voting epoch
start = "2021-08-01T00:00:00Z"
period = "90s"
uptime_threshold = 0.8

[epochs]
# first epoch to be voted for (do not leav this empty since the first epoch is well back in time
first = 1111

[voting_cronjob]
enabled = false
timeout = "10s"

[mirroring_cronjob]
enabled = false
timeout = "10s"

[contract_addresses]
mirroring = "0x0000000"
voting = "0x0000000"
