[db]
host = "localhost"   # from env DB_HOST
port = 3306          # from env DB_PORT
database = "flare_indexer"      # from env DB_DATABASE
username = "flareindexeruser"   # from env DB_USERNAME
password = ""                   # from env DB_PASSWORD
log_queries = false

[logger]
level = "DEBUG"
file = "./logs/flare-indexer.log"
console = false

[metrics]
# used for prometheus metrics of the indexer
# currently, no specific data are included in the metrics in addition to the default ones
# prometheus_address = "localhost:2112"

[chain]
node_url = "https://coston2-api-tracer.flare.network"  # from env CHAIN_NODE_URL
address_hrp = "costwo"
chain_id = 114
eth_rpc_url = "https://coston2-api.flare.network/ext/C/rpc"  # from env ETH_RPC_URL
private_key_file = "./private_key.txt"  # from env PRIVATE_KEY_FILE

[x_chain_indexer]
enabled = false

[p_chain_indexer]
enabled = true
timeout = "5s"
start_index = 0
batch_size = 100

[uptime_cronjob]
enabled = true
timeout = "30s"
enable_voting = true
start = 1662580800
period = "3600s"
uptime_threshold = 0.8
delete_old_uptimes_epoch_threshold = 5

[voting_cronjob]
enabled = true
timeout = "10s"
first = 183585

[contract_addresses]
voting = "0x694905ca5f9F6c49f4748E8193B3e8053FA9E7E4"  # from env VOTING_CONTRACT_ADDRESS
